development:
  adapter: postgresql
  encoding: unicode
  database: product_ping_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: product_ping_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: product_ping_production
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
